apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: harvester
  namespace: pipelines
  name: harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harvester
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app: harvester
    spec:
      imagePullSecrets:
        - name: ecr-local
      containers:
        - env:
            - name: GRPC_PYTHON_BUILD_SYSTEM_OPENSSL
              value: "1"
            - name: GRPC_PYTHON_BUILD_SYSTEM_ZLIB
              value: "1"
          image: 084981688622.dkr.ecr.us-east-1.amazonaws.com/honeycomb:scix-harvester-pipeline-v0.0.2
          imagePullPolicy: Always
          name: harvester
          resources: 
            requests:
              memory: "1000Mi"
              cpu: "500m"
            limits:
              memory: "1200Mi"
              cpu: "1000m"
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
